### ISSUE TITLE
Question: I cant find Social Media profiles of Organizations and People in any Ring

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterApps/Simplified#83]
Social Media profiles like FB, G+, LinkedIn, etc

**Comment by miyconst** [comment]
@atifwaqar thank you for the question, you can't find any because there is no such.

We are currently working hard to stop using `Simplified` and provide facilities so the apps will be able to use their own view-model. This means `Simplified` data model will not be extended with extra classes for the social media profile, but you can do that inside your application.
