### ISSUE TITLE
Why `master-v2.4` branch is so far behind `master`?

### ISSUE THREAD

**Issue by miyconst** [StarcounterApps/Simplified#98]
The readme say:

>**`master-v2.4`**: included in Starcounter 2.4, `master` should be always merged to here

But @warpech, @Joltrix, @un-tone, @Mihaiii, and @PatrykSzwer [didn't do that](https://github.com/StarcounterApps/Simplified/compare/master-v2.4...master?expand=1).

**Comment by warpech** [comment]
I believe it should be merged by principle. 

I am on not on 2.4 yet, so I suggest someone who can test it in 2.4 does that.

**Comment by Mihaiii** [comment]
How can I test it without publishing?
In 2.3 I used to reference the local dll, but in 2.4 I can't.

**Comment by per-samuelsson** [comment]
> How can I test it without publishing?

You can, and should, let TC run a personal build for you. Are you familiar with how to? If not, I can help explain it to you!

Now builds are broken because it was pushed, so would be good fixing that.

**Comment by Mihaiii** [comment]
Really sorry for that. Merge is now reverted.

Yes, I will make a custom build and see how it all goes from there.

**Comment by per-samuelsson** [comment]
> Really sorry for that. Merge is now reverted.

Cool. Can happen to anyone.

> Yes, I will make a custom build and see how it all goes from there.

👍 

From quickly skimming error, it looked like merge dropped `<StarcounterCompatibility>2.4</StarcounterCompatibility>` from `.csproj`-file. Which, I guess, can only happen if 2.3 was branched off of 2.4 at some point, and not the other way around. Anyway, could be as simple as just making sure that is added manually after merge.

**Comment by miyconst** [comment]
The `master-v2.4` branch is now up to date.

**Comment by PatrykSzwer** [comment]
Unfortunately `master-v2.4` is still out of date. Currently there are even files that doesn't exists on master-v.2.4 but does on master. Because of revert commit done by Mihai https://github.com/StarcounterApps/Simplified/commit/7c729ab20cce37d4efdba45c9f9737cc2d666073
files like `WebSettings` and many other changes are not included in `master-v2.4` even if github shows that master-2.4 is up to date with master.

**Comment by miyconst** [comment]
Maybe it would be better to drop the `master-v2.4` branch and do it again from the `master` branch? Are there any `2.4` specific changes/features?

**Comment by warpech** [comment]
Yes there are: https://github.com/StarcounterApps/Simplified/issues/100

**Comment by warpech** [comment]
I propose to manually copy files from `master` to `master-v2.4` and pick the missing files by hand. Remember to make sure to repeat the work from https://github.com/StarcounterApps/Simplified/issues/100 on these new files.

**Comment by miyconst** [comment]
[Replace QueryResultRows with IEnumerable](https://github.com/StarcounterApps/Simplified/issues/100) is only in `2.4`, but it's not any custom logic, just some code sugaring, can easily be replicated after fresh copy-paste from `master`.

**Comment by warpech** [comment]
Thanks for looking into this @Mihaiii, @PatrykSzwer and @miyconst. Is the issue solved now?

**Comment by warpech** [comment]
@habib535, @Mihaiii What is the reason for having two separate branches `master-v2.4` and `v2.4-nuget-package`?

Why can't make the NuGet package from `master-v2.4`, according to the diagram in README.md?

**Comment by habib535** [comment]
`v2.4-nuget-package` is removed.

**Comment by PatrykSzwer** [comment]
Guys, during review of @Mihaiii PR I've realized that there is a point in reverting all those changes and fixing current branch for 2.4. I suggest We do what @miyconst suggested - delete our current, messed up branch `master-2.4` and create a new one based on current `master`, and then just do PR with changes made only for 2.4 ([Replace QueryResultRows with IEnumerable](https://github.com/StarcounterApps/Simplified/issues/100) and compatibility attribute in csproj)

@Mihaiii could You do that?

**Comment by Mihaiii** [comment]
Why would that be better than merging #102 ?

**Comment by Mihaiii** [comment]
@miyconst Please let me know if you consider that creating a new branch (with a new name, right?) would be best so I can start doing the changes before moving back to the mapping version of SC.

**Comment by miyconst** [comment]
@Mihaiii my idea was to drop the `master-v2.4` branch and create it again from the `master` branch. The end goal is to have an up to date branch of Simplified compatible with Starcounter `2.4`. If it's easier to do another merge - I don't mind.

**Comment by PatrykSzwer** [comment]
> Why would that be better than merging #102 ? 

Because right now, git doesn't recognize differences between `master` and `master-2.4` and if there was any other change that we forgot to include, it will be really hard to find in future, if it cause any troubles. Also I'm not sure how "git problems" it could cause besides that. I think It would be just cleaner and safer.

And as @miyconst said, I would also suggest to delete current `master-v2.4` and create new one with same name.

**Comment by Mihaiii** [comment]
It doesn't recognize differences because it works on commits and reverting that merge was done directly on `master-v2.4`. Any new commit from now on that is made on `master` will be recognized on merge into `master-v2.4`. At lease this is what I got from what happened (I might be wrong).
I'll delete the `master-v2.4` at around 4-5 in the morning as there are currently builds on TC. I'll also won't have a separate branch that would merge into `master-v2.4` so that in the time between approval of that potential PR and the actual merge would be possible to make build in TC.

**Comment by Mihaiii** [comment]
Done. Closing.
